sonar.projectKey=jbiggs512_CSD_Student_Testing_Platform
sonar.organization=jbiggs512


# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=CSD_Student_Testing_Platform
#sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
#sonar.sources=.

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8

# Tell Sonar where to find the Python test coverage report
sonar.python.coverage.reportPaths=backend/coverage.xml

# Tell Sonar not to expect test coverage ON your actual test files
sonar.coverage.exclusions=backend/tests/**,**/*.example,backend/src/app/**/__init__.py
