name: Build
on:
  push:
    branches: ["master", "development"]
  pull_request:
    branches: ["master", "development"]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Install dependencies
        working-directory: ./backend
        run: uv sync

      - name: Run Pytest & Generate Coverage
        working-directory: ./backend
        run: uv run pytest

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@7006c4492b2e0ee0f816d36501671557c97f5995 # v8.1.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
